// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCncdTA5FcXCeX9YPndoqlVb16HIYidEnk',
    appId: '1:663253106721:web:fc1964a87620ee44e8a360',
    messagingSenderId: '663253106721',
    projectId: 'fir-portepros',
    authDomain: 'fir-portepros.firebaseapp.com',
    storageBucket: 'fir-portepros.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsa5bFI7wVwmMAV9BAforK3iYFg4h4Ji4',
    appId: '1:663253106721:android:102c76e20ceea8c0e8a360',
    messagingSenderId: '663253106721',
    projectId: 'fir-portepros',
    storageBucket: 'fir-portepros.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4G5MlIAv_4sCGRf2CxVqcwrzvg6sOIHM',
    appId: '1:663253106721:ios:3b8214d87872e703e8a360',
    messagingSenderId: '663253106721',
    projectId: 'fir-portepros',
    storageBucket: 'fir-portepros.appspot.com',
    iosBundleId: 'com.example.portepros2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4G5MlIAv_4sCGRf2CxVqcwrzvg6sOIHM',
    appId: '1:663253106721:ios:9a70d22eaabc2560e8a360',
    messagingSenderId: '663253106721',
    projectId: 'fir-portepros',
    storageBucket: 'fir-portepros.appspot.com',
    iosBundleId: 'com.example.portepros2.RunnerTests',
  );
}
